# Generated by Django 3.2.6 on 2021-08-21 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('idade', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, default='imagens/default.jpg', upload_to='imagens/%Y/%m/%d/%M/%f', verbose_name='Foto de perfil')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salário')),
                ('telefone_pessoal', models.CharField(blank=True, max_length=20, verbose_name='Telefone pessoal')),
                ('telefone_comercial', models.CharField(blank=True, max_length=25, verbose_name='Telefone de trabalho')),
                ('cpf', models.CharField(blank=True, max_length=25, unique=True, verbose_name='CPF')),
                ('data_contratacao', models.DateField(auto_now_add=True, verbose_name='Data de contratação')),
                ('demitido', models.BooleanField(default=False)),
                ('ultima_mudanca', models.DateField(auto_now=True, verbose_name='Última mudança')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
