# Generated by Django 3.2.6 on 2021-08-22 05:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20210822_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
