# Generated by Django 3.2.6 on 2021-08-22 05:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_empresa_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='gastos',
        ),
        migrations.AddField(
            model_name='empresa',
            name='despesas',
            field=models.ManyToManyField(blank=True, to='empresa.Despesa'),
        ),
    ]
