# Generated by Django 3.2.6 on 2021-08-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_auto_20210822_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='link',
            field=models.SlugField(blank=True, default='/', max_length=120),
        ),
    ]
