# Generated by Django 3.2.6 on 2021-08-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_auto_20210822_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(default='images/empresa.jpg', upload_to='images/company/%Y/%m/%d/%M/%f'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(default='images/logo.jpg', upload_to='images/company/%Y/%m/%d/%M/%f'),
        ),
    ]
