# Generated by Django 3.2.6 on 2021-08-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0012_auto_20210822_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
