# Generated by Django 3.2.6 on 2021-08-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_funcionario_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, default=0, unique=True),
        ),
    ]
