# Generated by Django 3.2.6 on 2021-08-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0015_alter_empresa_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='codigo',
            field=models.PositiveBigIntegerField(blank=True, default=0, unique=True),
        ),
    ]
