# Generated by Django 3.2.6 on 2021-08-25 02:05

from django.db import migrations, models
import empresa.models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0016_auto_20210824_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='codigo',
            field=models.PositiveBigIntegerField(blank=True, default=empresa.models.get_codigo, unique=True),
        ),
    ]
