# Generated by Django 3.2.6 on 2021-08-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_alter_funcionario_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='profissao',
            field=models.CharField(default='', max_length=120),
        ),
    ]
