# Generated by Django 3.2.6 on 2021-08-26 16:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0018_alter_funcionario_profissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, default='example', max_length=254),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor de mercado'),
        ),
    ]
