# Generated by Django 3.2.6 on 2021-08-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0019_auto_20210826_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, default='example@email.com', max_length=254),
        ),
    ]
