# Generated by Django 3.2.6 on 2021-08-26 16:24

from django.db import migrations, models
import empresa.models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0020_alter_funcionario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo',
            field=models.PositiveBigIntegerField(blank=True, default=empresa.models.get_codigo_empresa, null=True),
        ),
    ]
