# Generated by Django 3.2.6 on 2021-08-26 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0023_auto_20210826_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='codigo',
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACEITO', 'aceito'), ('RECUSADO', 'recusado'), ('EM ANDAMENTO', 'em_andamento'), ('INTERROMPIDO', 'interrompido'), ('FINALIZADO', 'finalizado')], max_length=15)),
                ('resposta', models.CharField(choices=[('ACEITO', 'aceito'), ('RECUSADO', 'recusado'), ('NENHUMA', 'nenhuma')], max_length=15)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresa.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
