# Generated by Django 3.2.6 on 2021-08-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0024_auto_20210826_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacao',
            old_name='Empresa',
            new_name='empresa',
        ),
    ]
