# Generated by Django 3.2.6 on 2021-08-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0025_rename_empresa_solicitacao_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='resposta',
            field=models.CharField(choices=[('aceito', 'ACEITO'), ('recusado', 'RECUSADO'), ('nenhuma', 'NENHUMA')], max_length=15),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('aceito', 'ACEITO'), ('recusado', 'RECUSADO'), ('em_andamento', 'EM ANDAMENTO'), ('interrompido', 'INTERROMPIDO'), ('finalizado', 'FINALIZADO')], max_length=15),
        ),
    ]
