# Generated by Django 3.2.6 on 2021-08-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0026_auto_20210826_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'EM ANDAMENTO'), ('interrompido', 'INTERROMPIDO'), ('finalizado', 'FINALIZADO')], max_length=15),
        ),
    ]
