# Generated by Django 3.2.6 on 2021-08-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0030_auto_20210829_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(default='images/logo.svg', upload_to='images/company/%Y/%m/%d/%M/%f'),
        ),
    ]
