# Generated by Django 3.2.6 on 2021-08-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0031_alter_empresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(default='images/logo.png', upload_to='images/company/%Y/%m/%d/%M/%f'),
        ),
    ]
